/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
// import Image from 'next/image'
import {useState} from 'react'
interface ICat {
	adaptability: number
	affection_level: number
	child_friendly: number
	energy_level: number
	dog_friendly: number
	id: string
	description: string
	intelligence: number
	name: string
	image: {
		url: string
	}
	life_span: string
	origin: string
	temperament: string
	weight: {
		metric: string
	}
	wikipedia_url: string
}
interface IHome {
	data: ICat[]
}
interface ISrc {
	setImgSrc: (cat: string) => void
}
const Home: React.FC<IHome> = ({data}) => {
	// const [cats, setCats] = useState(data)
	const [imgSrc, setImgSrc] = useState<string | (() => ISrc) | null>(null)
	console.log({data})
	// setCats(data)
	const getCats = () => {
		// setCats(data)
		console.log('called')
	}
	const handleOnError = () => {
		setImgSrc('https://media.makeameme.org/created/error-404-cannot.jpg')
	}
	return (
		<div>
			<Head>
				<title>CatzNation</title>
				<meta
					name='description'
					content='CatzNation app, generated by create next app to display various cats'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<h1>Cats</h1>
			<button onClick={getCats}>get cat</button>
			<div>
				{!data ? (
					<p>loading</p>
				) : (
					data?.map(cat => (
						<div key={cat?.id}>
							<h3>{cat?.name}</h3>
							<img src={cat?.image?.url} alt={cat?.name} />
							<p>{cat?.description}</p>
						</div>
					))
				)}
			</div>
		</div>
	)
}

export async function getServerSideProps() {
	const response = await fetch(`https://api.thecatapi.com/v1/breeds`, {
		headers: {limit: '10'}
	})
	const data = await response.json()
	return {props: {data}}
}
export default Home
